import { For, Show } from 'solid-js'
import { DASH } from '../lib/format'
// Inlined with Vite's ?raw suffix, not <img src>. An SVG behind <img> is an
// isolated document, so stroke="currentColor" would resolve to that document's
// own black; inlining lets the button's `color` reach the glyph, which is what
// makes the hover and active states move the icon with the surface.
import fullscreenIcon from '../assets/icons/fullscreen.svg?raw'
import exportIcon from '../assets/icons/export.svg?raw'
import './MapToolbar.css'

// The three map layers. More than one may be on at a time, so these are
// independent toggle buttons (aria-pressed), not a radio group.
const LAYERS = [
  { key: 'zones',    label: 'Zones',    hint: 'Show the red, orange and green zone rings' },
  { key: 'devices',  label: 'Devices',  hint: 'Show one dot per located device' },
  { key: 'shelters', label: 'Shelters', hint: 'Show the shelter markers' },
]

// The pill never says "live" unless the frames really are live. Two separate
// facts drive the wording: the socket's status, and where the frames come from.
const LIVE_TEXT = {
  connecting:   'Connecting',
  live:         'Stream live',
  reconnecting: 'Reconnecting',
  lost:         'Stream lost',
}

const DEMO_TEXT = {
  connecting:   'Demo loading',
  live:         'Demo stream',
  reconnecting: 'Demo stream',
  lost:         'Demo ended',
}

const SOURCE_SENTENCE = {
  live: 'Frames are arriving from the live supervisor.',
  demo: 'Frames are generated by the bundled demo stream, not by the live supervisor.',
}

export default function MapToolbar(props) {
  const isDemo = () => props.source === 'demo'

  // Anything unrecognised is treated as "connecting" rather than as "live":
  // an unknown state must never read as a healthy one.
  const status = () => (LIVE_TEXT[props.status] ? props.status : 'connecting')

  const labelText = () => (isDemo() ? DEMO_TEXT : LIVE_TEXT)[status()]

  const fpsNumber = () => (Number.isFinite(props.fps) ? Math.round(props.fps) : null)
  const fpsText = () => (fpsNumber() === null ? DASH : `${fpsNumber()}/s`)

  const layerOn = (key) => !!(props.layers && props.layers[key])

  // props.netLabel is the operator's OWN link — the Wi-Fi this browser sits on.
  // It is not the disaster area's cell congestion (that is a backend gap), so
  // every place it appears says whose connection it describes.
  const netSentence = () => {
    if (!props.netLabel) return ''
    const quality = props.netQuality ? ` — ${props.netQuality}` : ''
    return `Console link (this browser): ${props.netLabel}${quality}. ` +
           `That is your own connection, not the disaster area's network.`
  }

  const streamSentence = () => {
    const rate = fpsNumber() === null
      ? 'Frame rate unknown.'
      : `${fpsNumber()} frames per second.`
    return `${labelText()}. ${rate} ${SOURCE_SENTENCE[isDemo() ? 'demo' : 'live']}`
  }

  const pillTitle = () => {
    const net = netSentence()
    return net ? `${streamSentence()}\n${net}` : streamSentence()
  }

  return (
    <div class="map-toolbar" role="group" aria-label="Map controls">
      <div
        class="mt-stream"
        data-status={status()}
        data-source={isDemo() ? 'demo' : 'live'}
        title={pillTitle()}
      >
        <span class="mt-dot" aria-hidden="true" />
        <span class="mt-stream-label">{labelText()}</span>
        <span class="mt-stream-fps" aria-hidden="true">{fpsText()}</span>

        <span class="mt-sr" aria-live="polite">{streamSentence()}</span>
        <Show when={netSentence()}>
          <span class="mt-sr">{netSentence()}</span>
        </Show>
      </div>

      <div class="mt-layers" role="group" aria-label="Map layers">
        <For each={LAYERS}>
          {(layer) => (
            <button
              type="button"
              class="mt-seg"
              aria-pressed={layerOn(layer.key)}
              /* The visible word must survive into the accessible name, so the
                 hint is the tooltip only — a bare title would replace it. */
              aria-label={`${layer.label} layer`}
              title={layer.hint}
              onClick={() => props.onToggleLayer?.(layer.key)}
            >
              {layer.label}
            </button>
          )}
        </For>
      </div>

      <button
        type="button"
        class="mt-icon-btn mt-fullscreen"
        aria-label="Toggle fullscreen map"
        title="Fullscreen"
        onClick={() => props.onFullscreen?.()}
      >
        <span
          class="mt-icon-box mt-icon-box-22"
          aria-hidden="true"
          innerHTML={fullscreenIcon}
        />
      </button>

      <button
        type="button"
        class="mt-icon-btn mt-export"
        aria-label="Export the current event and devices as JSON"
        title="Export JSON"
        onClick={() => props.onExport?.()}
      >
        <span
          class="mt-icon-box mt-icon-box-22"
          aria-hidden="true"
          innerHTML={exportIcon}
        />
      </button>
    </div>
  )
}
